### ISSUE TITLE
Chore: Web version fails to upload `net::ERR_FAILED`

### ISSUE THREAD

**Issue by nelsonic** [dwyl/flutter-image-upload-demo#5]
Just tried:
https://dwyl.github.io/flutter-image-upload-demo/#/

<img width="1068" alt="image" src="https://github.com/dwyl/flutter-image-upload-demo/assets/194400/8e38b6cb-3015-4864-b936-950af8e67b47">

Shows an infinite loading spinner but no error message.

Open the console we see the following:
```sh
imgup.fly.dev/api/images:1     Failed to load resource: net::ERR_FAILED
```

@LuchoTurtle please investigate when you can. 🕵️‍♂️ 🔍 🙏

**Comment by nelsonic** [comment]
I think it might be related to _deployment_ of https://imgup.fly.dev/ ...

<img width="1482" alt="dwyl-imgup-deploy-fail" src="https://github.com/dwyl/flutter-image-upload-demo/assets/194400/470abd83-2fc6-4631-911d-1b353dc6b8f8">

Ref: https://github.com/dwyl/imgup/actions/runs/5596318684/jobs/10233193466#step:4:493

We need to mirror the deployment we have in the `MVP` which deploys fine:
<img width="1023" alt="image" src="https://github.com/dwyl/flutter-image-upload-demo/assets/194400/8e902992-1d30-461b-a81f-2488a7f67edc">

**Comment by LuchoTurtle** [comment]
This'll be fixed by https://github.com/dwyl/imgup/pull/102. Close when merged 👌

**Comment by nelsonic** [comment]
Working: https://dwyl.github.io/flutter-image-upload-demo/#/
<img width="913" alt="image" src="https://github.com/dwyl/flutter-image-upload-demo/assets/194400/cc335544-2946-4c58-afdd-d03a1065ea1d">

Thanks. 👌 

But ... we need to keep an eye on latency. ⏳ 
I think our `@home` internet is playing up so I will re-test tomorrow. 🐌 🤞 🐎
